version: "3"

services: 
  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prom-demo
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prom:/prometheus

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - prometheus

  node-exporter:
    image: prom/node-exporter:v1.2.2
    container_name: node-exporter
    ports:
      - '9100:9100'
    networks:
      - prometheus

  go-demo:
    build: ./go-demo-app
    image: go-demo:latest  
    ports:
      - '8090:8090'
    networks:
      - prometheus


networks:
  prometheus:

