global:
  scrape_interval: 15s 


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'go-demo'
    scrape_interval: 5s
    static_configs:
      - targets: ['go-demo:8090']
    
  - job_name: 'temperatures'
    scrape_interval: 10s
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['go-demo:8090']